PHP 8.2 Deprecated Dynamic Properties
spaze/phpstan-stripe pull request #17
Opened 2023-03-01 00:53 UTC by anthonyryan1

Use real properties in the stubs, drop support for PHP 7 because some type hints require union types. Given PHP 7 is EOL, this seems reasonable.

2023-03-01 01:02 UTC, anthonyryan1 commented
Currently working on the correct annotation for Retrofit/SubscriptionItems

2023-03-01 12:13 UTC, spaze commented
Thanks. From the top of my head, I think that annotating `SubscriptionItems` might work as follows

```
/** @var array<int, SubscriptionItem> */
public array $data
```

2023-03-01 12:14 UTC, spaze requested changes

2023-03-01 12:14 UTC, spaze commented on src/Retrofit/PaymentIntentNextAction.php
> +	 * @property 'redirect_to_url'|'use_stripe_sdk'|'alipay_handle_redirect'|'oxxo_display_details'|'verify_with_microdeposits' $type
I think this should use `@var` instead of `@property` and omit `$type`

2023-03-01 12:14 UTC, spaze commented on src/Retrofit/PaymentMethodCard.php
> +	 * @property 'amex'|'diners'|'discover'|'jcb'|'mastercard'|'unionpay'|'visa'|'unknown' $brand
Also `@var`

2023-03-05 17:50 UTC, spaze commented
I'm still not sure whether I'd like to drop PHP 7.x support (PHPStan alone requires PHP >= 7.2) Do you think adding the union types would also work only when a property with no type would be added?

For example this (check the `$default_payment_method` property):

```php
/**
 * @property string|\Stripe\PaymentMethod $default_payment_method
 */
class CustomerInvoiceSettings
{
	public StripeObject $custom_fields;
	public $default_payment_method;
	public string $footer;
	public StripeObject $rendering_options;
}
```

2023-03-05 23:17 UTC, anthonyryan1 commented
It's a good idea, but PHPStan wasn't recognizing it in my initial testing.

After trying again the internal PHPStan test shows:
```
 ------ ---------------------------------------------------------------------------------------------------------------- 
  Line   Retrofit/CustomerInvoiceSettings.php                                                                            
 ------ ---------------------------------------------------------------------------------------------------------------- 
  14     Property Spaze\PHPStan\Stripe\Retrofit\CustomerInvoiceSettings::$default_payment_method has no type specified.  
 ------ ---------------------------------------------------------------------------------------------------------------- 
```

I think it's treating it as a mixed property in external projects using these rules. We could use mixed, but will miss some errors.

2023-03-06 00:38 UTC, spaze approved these changes

2023-03-06 00:39 UTC, merged

2023-03-06 00:39 UTC, spaze commented
Makes sense, thanks for the contribution!

2023-03-06 02:00 UTC, spaze commented
Released in [3.0.0](https://github.com/spaze/phpstan-stripe/releases/tag/v3.0.0).